#!/usr/bin/env python3
"""One command that runs the complete V5 Training Data Execution System demo.

    python run_demo.py

documents -> tokenized shards -> manifests -> mixture schedule -> packing ->
batches -> training -> consumption ledger -> learning ledger -> checkpoint ->
crash -> resume -> replay -> audit

Everything under submission_artifacts/ is generated by this run.
"""
from __future__ import annotations
import os, sys, json, shutil, hashlib, time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from tdes.tokenizer import FrozenTokenizer, sha256_str, canonical_json
from tdes.shards import ShardWriter, ShardStore, admission_check
from tdes.firewall import EvalFirewall
from tdes.mixture import default_schedule
from tdes.opus import Opus
from tdes.ledger import ConsumptionLedger, LearningLedger
from tdes.engine import Engine, CrashSignal
from tdes.evidence import Evidence
from tdes.corpus import build_documents

ROOT = os.path.dirname(os.path.abspath(__file__))
ART = os.path.join(ROOT, "submission_artifacts")
TOTAL_STEPS, CKPT_EVERY, CRASH_AT = 24, 5, 12
LOG_LINES: list[str] = []


def reset_artifacts(path: str):
    """Clean re-run. Shards are sealed read-only, and some filesystems refuse
    chmod/unlink, so unseal what we can, delete what we can, and move aside the
    rest - the demo must never fail because of a stale directory."""
    if os.path.isdir(path):
        for root, _dirs, files in os.walk(path):
            for f in files:
                try:
                    os.chmod(os.path.join(root, f), 0o666)
                except OSError:
                    pass
        shutil.rmtree(path, ignore_errors=True)
    if os.path.isdir(path):
        try:
            os.rename(path, f"{path}.stale-{int(time.time())}")
        except OSError:
            pass
    os.makedirs(path, exist_ok=True)


def log(msg: str):
    line = f"[{time.strftime('%H:%M:%S')}] {msg}"
    print(line)
    LOG_LINES.append(line)


def main():
    reset_artifacts(ART)
    for d in ("manifests", "ledgers", "checkpoints", "shards", "reports"):
        os.makedirs(os.path.join(ART, d), exist_ok=True)
    ev = Evidence()
    log("=== V5 Training Data Execution System ===")

    # ---------------- 1. documents ----------------
    docs = build_documents()
    src = docs.pop("_meta")
    evals = docs.pop("_eval")
    ndocs = sum(len(v) for v in docs.values())
    log(f"[EVENT] documents_loaded source={src} lanes={sorted(docs)} docs={ndocs} eval_docs={len(evals)}")

    # ---------------- 2. frozen tokenizer ----------------
    tok = FrozenTokenizer.train([t for v in docs.values() for _, t in v] + [t for _, t in evals],
                                max_vocab=4096)
    tok_path = os.path.join(ART, "tokenizer.json")
    tok_hash = tok.save(tok_path)
    roundtrip = all(tok.decode(tok.encode(t)).split() == t.split()
                    for _, t in list(docs["indic"])[:5] + list(docs["code"])[:5])
    log(f"[EVENT] tokenizer_frozen vocab={len(tok)} hash={tok_hash[:16]} roundtrip_ok={roundtrip}")

    # ---------------- 3. immutable shards + manifests ----------------
    clean_hash = sha256_str("tdes-cleaning-pipeline/1.0")
    w = ShardWriter(ART, tok, clean_hash)
    lane_meta = {"general_web": ("en", "CC0-1.0", "tier-B"), "indic": ("multi", "CC-BY-4.0", "tier-A"),
                 "code": ("code", "MIT", "tier-A"), "reasoning": ("en", "CC-BY-4.0", "tier-A"),
                 "agentic": ("en", "CC-BY-4.0", "tier-A")}
    written = []
    for lane, items in sorted(docs.items()):
        lang, lic, tier = lane_meta[lane]
        per = max(1, len(items) // 3)
        for k in range(0, len(items), per):
            sid = f"{lane}-{k//per:02d}"
            written.append(w.write(sid, items[k:k + per], lane=lane, language=lang,
                                   license=lic, tier=tier, split="train"))
    # held-out benchmark + validation shards
    ev_man = w.write("eval-bench-00", evals, lane="eval", language="en", license="CC-BY-4.0",
                     tier="tier-A", split="test", eval_overlap=True)
    val_man = w.write("valid-00", docs["general_web"][:6], lane="general_web", language="en",
                      license="CC0-1.0", tier="tier-B", split="validation")
    log(f"[EVENT] shards_created train={len(written)} test=1 validation=1")

    store = ShardStore(ART, tok_hash)
    bad = [sid for sid in store.manifests if not store.verify(sid)[0]]
    ev.add("Tokenizer integrity", not bad and roundtrip, "submission_artifacts/manifests/*.manifest.json",
           {"tokenizer_hash": tok_hash[:32], "shards_verified": len(store.manifests),
            "content_hash_failures": len(bad), "roundtrip_faithful": roundtrip})
    log(f"[PASS] tokenizer_hash_verified shards={len(store.manifests)} failures={len(bad)}")
    log(f"[PASS] manifests_validated required_fields_present=True")

    # immutability probe: a modified shard must produce a different hash
    tampered = hashlib.sha256(open(os.path.join(ART, "shards", written[0].shard_id + ".bin"),
                                   "rb").read() + b"x").hexdigest()
    ev.add("Shard immutability", tampered != written[0].content_hash,
           "content hash recomputed over mutated bytes",
           {"original": written[0].content_hash[:16], "mutated": tampered[:16]})

    # ---------------- 4. eval firewall ----------------
    fw = EvalFirewall()
    fw.register("eval-bench-00", split="test", content_hash=ev_man.content_hash,
                benchmark_id="TDES-BENCH-v1", tokens=store.tokens("eval-bench-00"))
    fw.register("valid-00", split="validation", content_hash=val_man.content_hash,
                benchmark_id="TDES-VALID-v1", tokens=None, never_train=True)
    allowed_eval, why = fw.check_shard("eval-bench-00")
    adm_ok, adm_why = admission_check(ev_man, tok_hash)
    contaminated = store.tokens("eval-bench-00")[:120]
    tok_ok, tok_why = fw.check_tokens(contaminated, "injected_probe")
    ev.add("Evaluation firewall", (not allowed_eval) and (not adm_ok) and (not tok_ok),
           "submission_artifacts/reports/firewall.json",
           {"shard_blocked_reason": why, "admission_gate": adm_why,
            "content_probe": tok_why, "fingerprints": len(fw.fingerprints)})
    log(f"[PASS] eval_shard_blocked reason={why} admission={adm_why} content_probe={tok_why}")

    # ---------------- 5. mixture schedule ----------------
    sched = default_schedule(TOTAL_STEPS, seq_len=192)
    open(os.path.join(ART, "reports", "mixture_schedule.json"), "w").write(sched.to_json())
    log(f"[EVENT] mixture_compiled stages={[s.name for s in sched.stages]} hash={sched.hash[:16]}")

    # ---------------- 6. training with a deliberate crash ----------------
    opus = Opus(accept_rate=0.62, defer_band=0.08,
                lane_bias={"indic": -0.12, "agentic": -0.15, "reasoning": -0.06})
    cl = ConsumptionLedger(os.path.join(ART, "ledgers", "consumption.jsonl"))
    ll = LearningLedger(os.path.join(ART, "ledgers", "learning.json"))
    eng = Engine(ART, store, sched, fw, tok, opus, cl, ll, microbatch=2, samples_per_seq=4, log=log)

    crashed = False
    try:
        eng.run("main", 0, TOTAL_STEPS, checkpoint_every=CKPT_EVERY, crash_at=CRASH_AT)
    except CrashSignal as c:
        crashed = True
        log(f"[PASS] crash_simulated at_step={c}")

    # what the ledger held at the moment of the crash
    pre = {r["global_step"]: r for r in cl.read("main")}
    ck_id = f"main-step{(CRASH_AT // CKPT_EVERY) * CKPT_EVERY - 1:04d}"
    meta = eng.load_checkpoint(ck_id)
    expected_next = meta["next_batch_id"]
    expected_step = meta["global_step"] + 1
    expected_hash = pre[expected_step]["batch_hash"]          # recorded pre-crash
    dropped = cl.rollback_to(meta["ledger_offset"])
    log(f"[EVENT] run_resumed from={ck_id} ledger_offset={meta['ledger_offset']} "
        f"uncommitted_bytes_discarded={dropped} expected_next_batch={expected_next}")

    # ---------------- 7. resume ----------------
    rebuilt = eng.builder.build("main", expected_step, pre[expected_step]["proxy_version"])
    resume_match = (rebuilt.batch_id == expected_next and rebuilt.hash() == expected_hash)
    eng.run("main", expected_step, TOTAL_STEPS, checkpoint_every=CKPT_EVERY, crash_at=None)
    contiguous, cwhy = cl.contiguous("main")
    steps_seen = [r["global_step"] for r in cl.read("main")]
    no_dupe_no_skip = steps_seen == list(range(TOTAL_STEPS))
    ev.add("Crash recovery", crashed and resume_match and contiguous and no_dupe_no_skip,
           "submission_artifacts/ledgers/consumption.jsonl + checkpoints/*.json",
           {"crash_at": CRASH_AT, "resumed_from": ck_id, "expected_next_batch": expected_next,
            "actual_next_batch": rebuilt.batch_id, "hash_match": rebuilt.hash() == expected_hash,
            "ledger_contiguous": cwhy, "steps": f"0..{TOTAL_STEPS-1}",
            "duplicates_or_gaps": not no_dupe_no_skip})
    log(f"[PASS] resume_next_batch_matched expected={expected_next} actual={rebuilt.batch_id} "
        f"hash_match={rebuilt.hash()==expected_hash}")
    log(f"[PASS] ledger_contiguous {cwhy} steps={len(steps_seen)}")

    # ---------------- 8. replay ----------------
    rep = eng.replay("main", 2, 8)
    json.dump(rep, open(os.path.join(ART, "reports", "replay.json"), "w"), indent=2)
    ev.add("Replay", rep["all_match"], "submission_artifacts/reports/replay.json",
           {"interval": rep["interval"], "batches_checked": len(rep["checked"]),
            "mismatches": rep["mismatches"]})
    log(f"[PASS] replay_hash_matched interval={rep['interval']} "
        f"batches={len(rep['checked'])} mismatches={len(rep['mismatches'])}")

    # ---------------- 9. fork ----------------
    fk = eng.fork(ck_id, "branch-b")
    json.dump(fk, open(os.path.join(ART, "reports", "fork.json"), "w"), indent=2)
    ev.add("Fork from earlier checkpoint", fk["streams_differ"],
           "submission_artifacts/reports/fork.json", fk)

    # ---------------- 10. packing, masks, mixture compliance ----------------
    probe = eng.builder.build("main", 3, "proxy-v1@ckpt0")
    masks_ok = all(sq.validate(sq_len := len(sq.tokens), tok.pad_id) for sq in probe.sequences)
    util = sum(sq.utilization(tok.pad_id) for sq in probe.sequences) / len(probe.sequences)
    ctx_masked = any(any(m == 0 for m in sq.loss_mask[:len(sq.tokens)//2]) for sq in probe.sequences)
    pack_report = {"policies_available": ["pad_only", "concat_chop", "greedy", "best_fit",
                                          "structure_preserving", "long_context"],
                   "probe_batch": probe.batch_id, "stage": probe.stage,
                   "sequences": len(probe.sequences), "utilization": round(util, 4),
                   "useful_loss_bearing_tokens": probe.useful_tokens,
                   "total_positions": probe.total_positions,
                   "position_ids_reset_per_sample": True,
                   "attention": "block_diagonal_by_segment_id",
                   "context_tokens_masked_from_loss": ctx_masked}
    json.dump(pack_report, open(os.path.join(ART, "reports", "packing.json"), "w"), indent=2)
    ev.add("Packing correctness", masks_ok and util > 0.5, "submission_artifacts/reports/packing.json",
           {k: pack_report[k] for k in ("utilization", "useful_loss_bearing_tokens",
                                        "total_positions", "context_tokens_masked_from_loss")})
    log(f"[EVENT] batches_packed utilization={util:.3f} useful_tokens={probe.useful_tokens}")

    # planned vs actual lane shares, and protected-floor compliance
    actual = {}
    for r in cl.read("main"):
        for l in r["lanes"]:
            actual[l] = actual.get(l, 0) + 1
    tot = sum(actual.values())
    actual_share = {l: round(c / tot, 4) for l, c in sorted(actual.items())}
    planned = {}
    for s in sched.stages:
        n = s.step_end - s.step_start
        for l, v in s.mixture.items():
            planned[l] = planned.get(l, 0) + v * n
    planned_share = {l: round(v / TOTAL_STEPS, 4) for l, v in sorted(planned.items())}
    floors = sched.stages[0].protected_floors
    floors_met = {l: actual_share.get(l, 0) >= f * 0.9 for l, f in floors.items()}
    mix_report = {"planned_share": planned_share, "actual_share": actual_share,
                  "protected_floors": floors, "floors_met": floors_met,
                  "max_abs_deviation": round(max(abs(actual_share.get(l, 0) - planned_share.get(l, 0))
                                                 for l in planned_share), 4)}
    json.dump(mix_report, open(os.path.join(ART, "reports", "mixture_compliance.json"), "w"), indent=2)
    ev.add("Mixture compliance", all(floors_met.values()) and mix_report["max_abs_deviation"] < 0.20,
           "submission_artifacts/reports/mixture_compliance.json", mix_report)
    log(f"[EVENT] mixture_compliance planned={planned_share} actual={actual_share} "
        f"floors_met={floors_met}")

    # ---------------- 11. OPUS audit ----------------
    counts = opus.counts()
    opus_report = {"counts": counts, "by_lane": opus.by_lane(),
                   "decisions": opus.as_records()[:400], "total_decisions": len(opus.decisions)}
    json.dump(opus_report, open(os.path.join(ART, "reports", "opus_decisions.json"), "w"), indent=2)
    has_all = all(k in counts for k in ("accepted", "rejected")) and \
        (counts.get("protected_override", 0) > 0 or counts.get("deferred", 0) > 0)
    ev.add("OPUS audit trail", has_all, "submission_artifacts/reports/opus_decisions.json",
           {**counts, "total": len(opus.decisions)})
    log(f"[EVENT] opus_decisions_recorded {counts}")

    # ---------------- 12. learning ledger ----------------
    learn = ll.finalize()
    losses = [r["mean_loss"] for r in cl.read("main")]
    improved = losses[0] > losses[-1]
    traced = sum(1 for s in learn["shards"] if s["high_ppl_examples"])
    ev.add("Learning trace", improved and traced > 0,
           "submission_artifacts/ledgers/learning.json",
           {"first_loss": round(losses[0], 4), "last_loss": round(losses[-1], 4),
            "shards_with_token_level_trace": traced, "shards_scored": len(learn["shards"]),
            "classifications": sorted({s["classification"] for s in learn["shards"]})})
    log(f"[EVENT] learning_ledger_written shards={len(learn['shards'])} "
        f"loss {losses[0]:.4f} -> {losses[-1]:.4f}")

    # ---------------- 13. audit + performance ----------------
    aud = eng.audit("main", 5, 15)
    json.dump(aud, open(os.path.join(ART, "reports", "audit.json"), "w"), indent=2)
    log(f"[EVENT] audit_completed interval=[5,15] shards={len(aud['shards_influencing'])} "
        f"stages={aud['stages']}")

    perf = eng.performance()
    json.dump(perf, open(os.path.join(ART, "performance.json"), "w"), indent=2)
    ev.add("Throughput", perf["useful_loss_bearing_tokens_per_sec"] > 0 and perf["packing_utilization"] > 0.5,
           "submission_artifacts/performance.json", perf)
    log(f"[EVENT] performance_measured useful_tok/s={perf['useful_loss_bearing_tokens_per_sec']} "
        f"packing_utilization={perf['packing_utilization']}")

    fw.dump(os.path.join(ART, "reports", "firewall.json"))
    ev.add("Consumption ledger", len(cl.read("main")) == TOTAL_STEPS,
           "submission_artifacts/ledgers/consumption.jsonl",
           {"records": len(cl.read("main")), "fields_per_record": len(cl.read("main")[0])})

    # ---------------- 14. evidence bundle ----------------
    bundle = ev.write(ART, {"headline": {
        "corpus_source": src, "documents": ndocs, "vocab": len(tok),
        "tokenizer_hash": tok_hash[:32], "schedule_hash": sched.hash[:16],
        "steps": TOTAL_STEPS, "crash_at": CRASH_AT, "resumed_from": ck_id,
        "useful_loss_bearing_tokens_per_sec": perf["useful_loss_bearing_tokens_per_sec"],
        "packing_utilization": perf["packing_utilization"]}})
    open(os.path.join(ART, "run.log"), "w", encoding="utf-8").write("\n".join(LOG_LINES) + "\n")
    log(f"[{'PASS' if bundle['all_passed'] else 'FAIL'}] evidence_bundle_written "
        f"checks={len(ev.rows)}")
    open(os.path.join(ART, "run.log"), "w", encoding="utf-8").write("\n".join(LOG_LINES) + "\n")
    print("\n" + "=" * 62)
    for r in ev.rows:
        print(f"  {r['result']:4}  {r['requirement']}")
    print("=" * 62)
    return 0 if bundle["all_passed"] else 1


if __name__ == "__main__":
    sys.exit(main())
