/* ============================================================================
   The chronology. One entry per mechanism, ordered by the date it ACTUALLY
   appeared (arXiv v1 submission, or the public release for non-paper items).
   `date` is ISO. `dateNote` says what the date IS, because "the paper" and
   "the release" are not always the same event and that is where errors hide.
   ========================================================================= */
const MECHANISMS = [
{
  id: "bahdanau", name: "Additive (Bahdanau) attention", short: "Attention itself",
  date: "2014-09-01", dateNote: "arXiv v1 1409.0473",
  paper: "Neural Machine Translation by Jointly Learning to Align and Translate",
  authors: "Bahdanau, Cho, Bengio", url: "https://arxiv.org/abs/1409.0473",
  tags: ["origin"], bonus: true,
  bill: "A fixed-length encoder vector was a bottleneck: long sentences got squeezed into one vector and the decoder lost the beginning.",
  how: "Let the decoder look back at every encoder state and learn a weight per position via a small feed-forward scoring net (a tanh MLP), then take a weighted sum.",
  buys: "Removes the fixed-vector bottleneck; alignment becomes learned and inspectable.",
  costs: "The scoring MLP is a per-pair neural net — slow, not a single matmul. Still recurrent, so no parallelism over time.",
  pick: "Historical. You would not build this today, but every later mechanism is a cost-reduction of this idea."
},
{
  id: "learned-abs", name: "Absolute learned positions", short: "A row per position",
  date: "2017-05-08", dateNote: "arXiv v1 1705.03122 (ConvS2S) — predates the Transformer",
  paper: "Convolutional Sequence to Sequence Learning",
  authors: "Gehring, Auli, Grangier, Yarats, Dauphin (FAIR)", url: "https://arxiv.org/abs/1705.03122",
  tags: ["position"],
  bill: "A non-recurrent model reads a set. Word order has to be supplied from outside.",
  how: "A second embedding table indexed by position; row t is added to the token vector at slot t. Later used by GPT-1 and BERT.",
  buys: "Maximally expressive inside the trained range — the model can learn anything it likes about position 37.",
  costs: "A hard wall. Row 4096 exists only if you trained it. There is no signal linking row 4095 to 4096, so it cannot extrapolate by even one token — they were only ever independent rows in a lookup.",
  pick: "Fixed, known, short context and you want simplicity. Never for a model whose context you intend to extend."
},
{
  id: "sdpa", name: "Scaled dot-product attention", short: "The baseline",
  date: "2017-06-12", dateNote: "arXiv v1 1706.03762",
  paper: "Attention Is All You Need",
  authors: "Vaswani et al. (Google)", url: "https://arxiv.org/abs/1706.03762",
  tags: ["core"], anchor: true,
  bill: "Bahdanau's scoring MLP was too slow, and recurrence blocked parallel training.",
  how: "Score = QKᵀ/√d_k, causal-mask the future to −∞, softmax each row, take the weighted sum of V. The whole sequence trains in parallel. √d_k keeps dot products in softmax's useful range as width grows.",
  buys: "Exact, global, parallel. Every token can reach every other token in one step. It is still the accuracy reference every approximation is measured against.",
  costs: "Two separate bills that everything after this is trying to pay. Compute grows ~T² (10k tokens = 100M scores). And at generation time the KV cache grows ~T per user and cannot be shared between users.",
  pick: "Short contexts, and as the correctness baseline. With FlashAttention it is still the right default well past the length people assume."
},
{
  id: "sinusoidal", name: "Sinusoidal positions", short: "Computed, not stored",
  date: "2017-06-12", dateNote: "arXiv v1 1706.03762 — same paper as SDPA",
  paper: "Attention Is All You Need (§3.5)",
  authors: "Vaswani et al. (Google)", url: "https://arxiv.org/abs/1706.03762",
  tags: ["position"],
  bill: "A stored position table cannot describe a position it never saw.",
  how: "sin/cos of position at geometrically spaced frequencies. A function of t, defined for every t, so nothing has to be stored or trained.",
  buys: "No parameters, no length wall by construction, and offsets are expressible as a linear function of the encoding.",
  costs: "Defined everywhere is not learned everywhere — a model trained on 512 has never had to use the far part of the function, and quality still degrades past training length. Less expressive than a learned table in-range.",
  pick: "When you want zero position parameters and a simple baseline. Largely superseded by RoPE in decoder LLMs."
},
{
  id: "relative-shaw", name: "Relative position embeddings", short: "Distance, not index",
  date: "2018-03-06", dateNote: "arXiv v1 1803.02155",
  paper: "Self-Attention with Relative Position Representations",
  authors: "Shaw, Uszkoreit, Vaswani (Google)", url: "https://arxiv.org/abs/1803.02155",
  tags: ["position"], bonus: true,
  bill: "Absolute indices are the wrong unit — what matters for language is how far apart two tokens are, not where they sit from the document start.",
  how: "Add a learned embedding of the clipped relative distance (i−j) into the attention score itself, rather than adding position to the input.",
  buys: "Translation-invariant: the same phrase behaves the same at position 5 and 500. This idea is the ancestor of RoPE, T5 bias and ALiBi.",
  costs: "Extra tensor work inside attention, and distances are clipped to a maximum, which reintroduces a (softer) horizon.",
  pick: "Rarely raw today; take its descendant RoPE instead. Worth knowing because it is where the field stopped thinking in absolute indices."
},
{
  id: "txl", name: "Transformer-XL segment recurrence", short: "Carry state across chunks",
  date: "2019-01-09", dateNote: "arXiv v1 1901.02860",
  paper: "Transformer-XL: Attentive Language Models Beyond a Fixed-Length Context",
  authors: "Dai, Yang, Yang, Carbonell, Le, Salakhutdinov", url: "https://arxiv.org/abs/1901.02860",
  tags: ["state", "position"], bonus: true,
  bill: "Chopping a document into fixed windows throws away all state at every boundary — context fragmentation.",
  how: "Cache the previous segment's hidden states and let the current segment attend into them (stop-gradient), plus a relative-position scheme that survives the shift.",
  buys: "Long effective context without quadratic cost; the first serious 'memory between chunks' design. Its descendant is the Memory Stream idea in LightningLM V4.",
  costs: "The carried state is read-only and decays; gradients do not flow across the boundary, so the model never learns to write it well.",
  pick: "When documents exceed your window and you cannot afford full attention — still the cheapest way to stop losing everything at a chunk edge."
},
{
  id: "sparse-transformer", name: "Sparse Transformer (strided/fixed patterns)", short: "Stop reading everything",
  date: "2019-04-23", dateNote: "arXiv v1 1904.10509",
  paper: "Generating Long Sequences with Sparse Transformers",
  authors: "Child, Gray, Radford, Sutskever (OpenAI)", url: "https://arxiv.org/abs/1904.10509",
  tags: ["compute", "sparse"], bonus: true,
  bill: "T² compute. Attention maps looked mostly empty — so why compute all of it?",
  how: "Fix a pattern in advance: each token attends to a local band plus a strided set of far positions, so information still routes globally in two hops.",
  buys: "O(T√T) attention, and the first credible demonstration that you can drop most of the matrix and still model long sequences (images, audio, text).",
  costs: "The pattern is chosen by a human, not the data — the useful key might simply not be in your pattern. Needs custom kernels to realise the theoretical saving.",
  pick: "When your data has known locality structure. Mostly of historical importance now: it is the ancestor of every learned-sparsity method below."
},
{
  id: "mqa", name: "Multi-Query Attention (MQA)", short: "One K/V head for all queries",
  date: "2019-11-06", dateNote: "arXiv v1 1911.02150",
  paper: "Fast Transformer Decoding: One Write-Head is All You Need",
  authors: "Noam Shazeer (Google)", url: "https://arxiv.org/abs/1911.02150",
  tags: ["memory"], turning: true,
  bill: "The KV cache — not compute — is what makes generation slow. Cache size scales with the number of K/V heads.",
  how: "Keep all the query heads, but share a single key head and a single value head across them.",
  buys: "Cuts KV cache and the memory bandwidth per decoded token by the number of heads — often 8–64×. Decoding gets dramatically faster.",
  costs: "Quality loss: heads lose their independent view of the sequence. Training-instability reports, and it is hard to retrofit cleanly.",
  pick: "Memory-bound serving where throughput dominates, or very small models. Most teams now take GQA instead as the middle setting.",
  note: "The most under-appreciated date on this timeline: it sat almost unused for 3½ years until inference cost became the binding constraint."
},
{
  id: "reformer", name: "Reformer (LSH attention)", short: "Hash to find neighbours",
  date: "2020-01-13", dateNote: "arXiv v1 2001.04451",
  paper: "Reformer: The Efficient Transformer",
  authors: "Kitaev, Kaiser, Levskaya (Google)", url: "https://arxiv.org/abs/2001.04451",
  tags: ["compute", "sparse"], bonus: true,
  bill: "Fixed sparsity patterns are guesses. Can the model find which keys matter, cheaply?",
  how: "Locality-sensitive hashing buckets similar queries and keys together, so attention is computed only inside buckets; plus reversible layers to cut activation memory.",
  buys: "O(T log T) with content-based rather than hand-drawn sparsity.",
  costs: "Hashing is approximate and adds constant overhead; needs several hash rounds to be reliable; the wins largely evaporated once exact attention got IO-efficient.",
  pick: "Rarely today. Its lasting contribution is the argument that sparsity should be learned from content."
},
{
  id: "topk", name: "Top-k / routed attention", short: "Let the content choose",
  date: "2020-03-12", dateNote: "arXiv v1 2003.05997",
  paper: "Efficient Content-Based Sparse Attention with Routing Transformers",
  authors: "Roy, Saffar, Vaswani, Grangier (Google)", url: "https://arxiv.org/abs/2003.05997",
  tags: ["sparse", "compute"],
  bill: "Keep exact softmax, but stop reading every key — and stop letting a human draw the pattern.",
  how: "Cluster queries and keys online (spherical k-means), then attend only within a cluster: each query reads the top-k most relevant keys and softmaxes over just those.",
  buys: "Content-based sparsity — the routing adapts to the data instead of a fixed stride, and the softmax over the chosen k is still exact.",
  costs: "The catch: naive top-k must still SCORE all T keys to know which k to keep, so you save the value work but not the scoring work. You therefore need a cheap proposal step (window, router, compressed index), which trades search cost against the risk of missing a useful key. Concentration of attention is empirical, not guaranteed.",
  pick: "When you need exact softmax over a long context and can afford a proposal mechanism. LightningLM V4 uses sparse 'G-layers' this way — with a budget cut from 1024 to 256 because of backward-kernel contention, an implementation limit rather than a law.",
  note: "The unresolved cost here — how to propose candidates cheaply — is precisely what NSA and DSA are built to answer five years later."
},
{
  id: "sliding-window", name: "Sliding-window attention", short: "Only look back w tokens",
  date: "2020-04-10", dateNote: "arXiv v1 2004.05150 (Longformer). Popularised in production by Mistral 7B, 2023-10-10, arXiv 2310.06825",
  paper: "Longformer: The Long-Document Transformer",
  authors: "Beltagy, Peters, Cohan (AI2)", url: "https://arxiv.org/abs/2004.05150",
  tags: ["compute", "memory", "sparse"],
  bill: "Both bills at once: T² compute and a cache that grows forever.",
  how: "Each token attends only to a fixed window of w recent tokens (plus, in Longformer, a few global tokens). Stacking L layers gives an effective receptive field of ~L×w.",
  buys: "Linear in T for both compute and cache — the cache stops growing entirely, which is the only property here that makes truly unbounded streaming possible.",
  costs: "Anything outside the window is gone unless a later layer relays it; retrieval across long distances degrades. Global tokens must be chosen by hand.",
  pick: "Streaming, chat with bounded history, or as the cheap layers in a hybrid stack. Wrong when the answer may depend on an exact token 500k back."
},
{
  id: "linear-attention", name: "Linear attention", short: "Drop softmax, keep a state",
  date: "2020-06-29", dateNote: "arXiv v1 2006.16236",
  paper: "Transformers are RNNs: Fast Autoregressive Transformers with Linear Attention",
  authors: "Katharopoulos, Vyas, Pappas, Fleuret", url: "https://arxiv.org/abs/2006.16236",
  tags: ["compute", "state"],
  bill: "Softmax's shared denominator forces every new query to revisit every individual old key. That coupling is what makes the cost quadratic.",
  how: "Replace exp(qᵀk) with φ(q)ᵀφ(k). Now q factors out of the sum, so all past pairs fold into one running state S = Σ φ(kⱼ)vⱼᵀ, read as y = φ(q)ᵀS. Fixed-size state after 10 or 10⁶ tokens.",
  buys: "Linear time, constant memory per step, and O(1) decoding — a genuine RNN at inference. Cost stops depending on length at all.",
  costs: "You give up positivity, normalisation, and competition between keys — memories interfere and state magnitude can grow unboundedly. Associative recall (\"what was that ID again?\") is measurably worse.",
  pick: "Very long or streaming workloads where exact recall is not the point, or as the majority of layers in a hybrid stack."
},
{
  id: "performer", name: "Performer (FAVOR+)", short: "Approximate softmax properly",
  date: "2020-09-30", dateNote: "arXiv v1 2009.14794",
  paper: "Rethinking Attention with Performers",
  authors: "Choromanski et al. (Google)", url: "https://arxiv.org/abs/2009.14794",
  tags: ["compute", "state"], bonus: true,
  bill: "Plain linear attention silently changes the function. Can you keep linear cost and still approximate real softmax with a guarantee?",
  how: "Random-feature maps that give an unbiased estimate of the softmax kernel, with positivity constraints for stability (FAVOR+).",
  buys: "Linear cost with an actual approximation bound, and it can be swapped into a pretrained softmax model.",
  costs: "Variance: the estimate is noisy, and you need many random features for accuracy, which eats the saving. In practice quality trailed exact attention.",
  pick: "Mostly superseded. Worth citing when someone claims linear attention has no theory behind it."
},
{
  id: "fast-weight-delta", name: "Delta rule in linear attention", short: "Correct, don't just add",
  date: "2021-02-22", dateNote: "arXiv v1 2102.11174",
  paper: "Linear Transformers Are Secretly Fast Weight Programmers",
  authors: "Schlag, Irie, Schmidhuber", url: "https://arxiv.org/abs/2102.11174",
  tags: ["state"],
  bill: "A fixed-size state that only ever ADDS cannot revise. Write 40 for key A, later want 55, and you get 95. The state size is not the problem — the write rule is.",
  how: "Before writing, read what the state currently returns for this key, compute the gap, and write only the correction: S ← S + (v − Sk)kᵀ. This is Widrow–Hoff's 1960 delta rule, applied to a fast-weight memory.",
  buys: "The state can now be edited, not just accumulated. Associative recall improves sharply.",
  costs: "The update is sequential-looking, which made it hard to train fast on GPUs — this is exactly why it stayed niche for three years.",
  pick: "As the write rule inside any fixed-state design. Rarely alone; see Gated DeltaNet."
},
{
  id: "rope", name: "RoPE (Rotary Position Embedding)", short: "Rotate, don't add",
  date: "2021-04-20", dateNote: "arXiv v1 2104.09864",
  paper: "RoFormer: Enhanced Transformer with Rotary Position Embedding",
  authors: "Su, Lu, Pan, Wen, Liu", url: "https://arxiv.org/abs/2104.09864",
  tags: ["position"], turning: true,
  bill: "Adding position to the input mixes 'what' with 'where'. Relative schemes fixed that but cost extra tensors inside attention.",
  how: "Treat dimension pairs as 2-D vectors and rotate each by position×θ, with different pairs rotating at different rates. In the dot product the absolute rotations cancel and only R((i−j)θ) survives — the score depends on distance, for free.",
  buys: "Relative behaviour at zero parameter cost, no lookup table, evaluable at any position, and it composes with everything. It is the default in Llama, Qwen, DeepSeek, Mistral.",
  costs: "Defined at 256k is not trained at 256k — quality collapses past the trained length without help. Rotation frequencies are a hyperparameter (θ base) that later methods spend their time repairing.",
  pick: "Default choice for any new decoder LLM. Assume you will also need one of the extension methods below."
},
{
  id: "alibi", name: "ALiBi (Attention with Linear Biases)", short: "Just penalise distance",
  date: "2021-08-27", dateNote: "arXiv v1 2108.12409",
  paper: "Train Short, Test Long: Attention with Linear Biases Enables Input Length Extrapolation",
  authors: "Press, Smith, Lewis", url: "https://arxiv.org/abs/2108.12409",
  tags: ["position"],
  bill: "Everyone wanted train-short-test-long, and no position scheme actually delivered it.",
  how: "No position embedding at all. Add a fixed, head-specific linear penalty −m·(i−j) directly to the attention scores. Distant tokens are simply discounted, with each head using a different slope.",
  buys: "Genuine extrapolation well past training length, no parameters, trivial to implement, and fast.",
  costs: "It is a monotonic recency prior baked into the architecture — the model structurally cannot prefer a token 100k back over a nearby one, which hurts true long-range retrieval (needle-in-a-haystack). Encodes no absolute position.",
  pick: "Streaming or where recency genuinely dominates and you need extrapolation for free. Avoid for retrieval-heavy long-context agents."
},
{
  id: "flash", name: "FlashAttention", short: "Same maths, right memory",
  date: "2022-05-27", dateNote: "arXiv v1 2205.14135",
  paper: "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness",
  authors: "Dao, Fu, Ermon, Rudra, Ré (Stanford)", url: "https://arxiv.org/abs/2205.14135",
  tags: ["compute"], turning: true, bonus: true,
  bill: "By 2022 everyone assumed the T² matrix must be approximated. But the real bottleneck was never FLOPs — it was writing that T×T matrix to HBM and reading it back.",
  how: "Tile Q/K/V into SRAM, compute softmax with a running (online) normaliser, and never materialise the full attention matrix. Exact result, recomputed in the backward pass.",
  buys: "2–4× faster and O(T) memory instead of O(T²), with bit-exact softmax attention. No approximation, no quality question.",
  costs: "It does not change the asymptotics — T² work is still T² work, just efficient. Needs hand-written kernels per hardware generation.",
  pick: "Always. Enable it and re-measure before you adopt any approximate method.",
  note: "This is the plot twist of the whole timeline: it made exact attention cheap enough that most of the 2019–2020 approximation wave lost its reason to exist."
},
{
  id: "gqa", name: "Grouped-Query Attention (GQA)", short: "The middle setting",
  date: "2023-05-22", dateNote: "arXiv v1 2305.13245",
  paper: "GQA: Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints",
  authors: "Ainslie et al. (Google)", url: "https://arxiv.org/abs/2305.13245",
  tags: ["memory"],
  bill: "MHA's cache is too big; MQA's quality drop is too painful. And nobody wanted to pretrain from scratch to find out.",
  how: "Split query heads into G groups, one K/V head per group (MHA = G heads, MQA = G 1). Crucially, uptrain an existing MHA checkpoint into GQA with ~5% of original compute.",
  buys: "Most of MQA's memory saving at near-MHA quality, and you can convert models you already trained. Now the default in Llama 2/3, Mistral, and most open models.",
  costs: "It only changes the constant. The cache still grows linearly with T — at 1M tokens you still store 1M positions. It postpones the problem rather than solving it.",
  pick: "Default for any production decoder today. Insufficient on its own for million-token contexts."
},
{
  id: "pi", name: "Position Interpolation (PI)", short: "Squeeze positions inward",
  date: "2023-06-27", dateNote: "arXiv v1 2306.15595",
  paper: "Extending Context Window of Large Language Models via Positional Interpolation",
  authors: "Chen, Wong, Chen, Tian (Meta)", url: "https://arxiv.org/abs/2306.15595",
  tags: ["position", "extension"], bonus: true,
  bill: "A RoPE model trained at 2k breaks at 8k. Retraining from scratch costs millions.",
  how: "Rather than extrapolating to unseen rotation angles, linearly scale positions down so 8k maps into the 2k range the model already knows. A short fine-tune restores quality.",
  buys: "Context extension for ~1000 steps of fine-tuning instead of a new pretrain. Opened the entire context-extension field.",
  costs: "Uniform squeezing crushes high-frequency dimensions, which is exactly where fine local word-order information lives. Needs fine-tuning.",
  pick: "When you can fine-tune. If you cannot, NTK-aware/YaRN descend directly from this."
},
{
  id: "ntk", name: "NTK-aware scaled RoPE", short: "Stretch low frequencies only",
  date: "2023-06-30", dateNote: "Community post, NOT a paper: Reddit r/LocalLLaMA (post 14lz7j5) by u/bloc97, late June 2023; corroborated by HF text-generation-inference issue #512, 30 Jun 2023",
  paper: "NTK-Aware Scaled RoPE allows LLaMA models to have extended (8k+) context size without any fine-tuning",
  authors: "bloc97 (community)", url: "https://www.reddit.com/r/LocalLLaMA/comments/14lz7j5/ntkaware_scaled_rope_allows_llama_models_to_have/",
  tags: ["position", "extension"],
  bill: "PI needed fine-tuning and blurred fine detail. People wanted longer context tonight, on a model they had already downloaded.",
  how: "Borrowing the neural-tangent-kernel intuition that networks struggle to learn high frequencies: instead of scaling all dimensions equally, change the RoPE base θ so low-frequency (long-range) dimensions stretch while high-frequency (local) ones are left nearly untouched.",
  buys: "Meaningful context extension with NO fine-tuning at all — a config change. Spread through the open-weights community in days.",
  costs: "Heuristic with no guarantee; quality still degrades at large scale factors, and it is not optimal at either frequency extreme. Non-uniform behaviour across dimensions is hard to reason about.",
  pick: "Quick extension of an existing checkpoint when you cannot fine-tune. If you can spend a little training, YaRN is strictly better.",
  note: "A genuine date trap: it has no paper and no arXiv ID. Cite the Reddit post — that is the primary source."
},
{
  id: "yarn", name: "YaRN", short: "Extension, done properly",
  date: "2023-08-31", dateNote: "arXiv v1 2309.00071 (submitted 31 Aug 2023, announced Sept 2023)",
  paper: "YaRN: Efficient Context Window Extension of Large Language Models",
  authors: "Peng, Quesnelle, Fan, Shippole", url: "https://arxiv.org/abs/2309.00071",
  tags: ["position", "extension"],
  bill: "PI blurred local detail; NTK-aware was an untuned heuristic. Neither handled the middle frequencies well, and both disturbed attention entropy.",
  how: "'NTK-by-parts': classify RoPE dimensions by whether their wavelength fits inside the trained context — interpolate the ones that do not, leave the ones that do, blend in between — plus a temperature correction to attention logits to restore entropy.",
  buys: "State-of-the-art extension quality at ~10× fewer tokens and 2.5× fewer steps than PI fine-tuning, and it composes with sliding-window inference. Used by Qwen and many open models.",
  costs: "More hyperparameters and more implementation surface than NTK; still an after-the-fact repair on a model trained short, not a model that learned long.",
  pick: "The default when extending an existing RoPE model and you can afford a short fine-tune."
},
{
  id: "sinks", name: "Attention sinks / StreamingLLM", short: "Keep the first few tokens",
  date: "2023-09-29", dateNote: "arXiv v1 2309.17453",
  paper: "Efficient Streaming Language Models with Attention Sinks",
  authors: "Xiao, Tian, Chen, Han, Lewis (MIT/Meta/CMU)", url: "https://arxiv.org/abs/2309.17453",
  tags: ["memory", "discovery"],
  bill: "Naive sliding-window caching should work for infinite streams — but as soon as the very first tokens are evicted, perplexity explodes. Nobody knew why.",
  how: "The finding: softmax must sum to 1, so when a head has nothing it wants, it dumps probability mass on the first few tokens. Those tokens are a bias sink, not content. Fix: always keep ~4 initial tokens in the cache alongside the rolling window.",
  buys: "Stable generation over millions of tokens with a constant-size cache, and a real mechanistic explanation of a bug. Four tokens is the entire cost.",
  costs: "It stabilises the stream; it does not extend memory. Anything evicted is still gone — this is not long context, it is infinite streaming with a short memory.",
  pick: "Any always-on streaming deployment. Pair with sliding window; do not mistake it for long-context capability.",
  note: "The rare entry here that is a scientific discovery about attention's behaviour rather than a cost trade."
},
{
  id: "mamba", name: "Mamba / selective SSM", short: "The state-space challenger",
  date: "2023-12-01", dateNote: "arXiv v1 2312.00752",
  paper: "Mamba: Linear-Time Sequence Modeling with Selective State Spaces",
  authors: "Gu, Dao", url: "https://arxiv.org/abs/2312.00752",
  tags: ["state"], bonus: true,
  bill: "Linear-attention/SSM states were input-independent: they compressed everything equally and could not choose what to remember.",
  how: "Make the state-space parameters functions of the input (selectivity), so the model can decide to keep or forget per token, with a hardware-aware parallel scan to keep it fast.",
  buys: "Transformer-quality language modelling at linear time and constant-memory inference; 5× higher decoding throughput.",
  costs: "Weaker at exact copying/associative recall than attention; needs custom kernels; pure-SSM stacks generally lose to hybrids in practice.",
  pick: "Long streaming workloads, or as the cheap majority layers in a hybrid. Its real influence here is the gating idea that Gated DeltaNet fuses with the delta rule."
},
{
  id: "mla", name: "Multi-head Latent Attention (MLA)", short: "Compress the cache, don't drop heads",
  date: "2024-05-07", dateNote: "arXiv v1 2405.04434 (DeepSeek-V2)",
  paper: "DeepSeek-V2: A Strong, Economical, and Efficient Mixture-of-Experts Language Model",
  authors: "DeepSeek-AI", url: "https://arxiv.org/abs/2405.04434",
  tags: ["memory"],
  bill: "MQA/GQA save cache by throwing heads away, and pay for it in quality. Could you keep the heads and compress instead?",
  how: "Project K and V down into a shared low-rank latent vector and cache only that, decompressing per head on the fly. Because RoPE does not commute with the down-projection, a small number of dimensions carry position separately (decoupled RoPE).",
  buys: "~93% KV-cache reduction versus MHA while matching or beating MHA quality — it dominates GQA on the memory/quality curve rather than trading against it.",
  costs: "Real architectural complexity (the decoupled-RoPE split is fiddly), extra compute to decompress, and you cannot uptrain an existing GQA model into it for free.",
  pick: "New large models where serving memory is the binding constraint and you control pretraining. It is also why some recent designs apply RoPE to only a slice of the head dimensions."
},
{
  id: "deltanet", name: "DeltaNet (parallelised delta rule)", short: "The delta rule made trainable",
  date: "2024-06-10", dateNote: "arXiv v1 2406.06484",
  paper: "Parallelizing Linear Transformers with the Delta Rule over Sequence Length",
  authors: "Yang, Wang, Zhang, Kim (MIT/others)", url: "https://arxiv.org/abs/2406.06484",
  tags: ["state"],
  bill: "The 2021 delta rule was better at recall but looked inherently sequential, so nobody could train it at scale.",
  how: "Reformulate the sequence of delta updates as products of Householder matrices, giving a chunkwise-parallel algorithm that maps onto GPUs.",
  buys: "The delta rule at standard LM scale — sharply better associative recall than plain linear attention, at linear cost.",
  costs: "Still a fixed-size state, so capacity is bounded; no forgetting mechanism, so stale information lingers; needs bespoke kernels.",
  pick: "As the linear-state layer type in a hybrid stack. LightningLM V4 uses DeltaNet layers for 6 of every 8."
},
{
  id: "gated-deltanet", name: "Gated DeltaNet", short: "Edit precisely, forget quickly",
  date: "2024-12-09", dateNote: "arXiv v1 2412.06464 (ICLR 2025)",
  paper: "Gated Delta Networks: Improving Mamba2 with Delta Rule",
  authors: "Yang, Kautz, Hatamizadeh (NVIDIA/MIT)", url: "https://arxiv.org/abs/2412.06464",
  tags: ["state"],
  bill: "Two complementary tools existed separately: gating (Mamba2) erases fast but bluntly; the delta rule edits precisely but never forgets.",
  how: "Combine them into one gated delta update — a decay/gate term controls global forgetting while the delta term makes the targeted correction — with a chunkwise-parallel kernel.",
  buys: "Beats Mamba2 and DeltaNet on language modelling, recall and long-context; the strongest fixed-state layer at time of writing. Adopted in Qwen3-Next-style hybrids.",
  costs: "Still bounded state: it cannot reproduce an exact token from 500k back the way attention can. More hyperparameters, custom kernels, and hybrid stacks (some attention layers) are needed for peak quality.",
  pick: "The linear-state layer to reach for today, in a hybrid with a few real attention layers."
},
{
  id: "nsa", name: "Native Sparse Attention (NSA)", short: "Sparsity you train with",
  date: "2025-02-16", dateNote: "arXiv v1 2502.11089",
  paper: "Native Sparse Attention: Hardware-Aligned and Natively Trainable Sparse Attention",
  authors: "DeepSeek-AI", url: "https://arxiv.org/abs/2502.11089",
  tags: ["sparse", "compute"],
  bill: "Every earlier sparse method was bolted onto a dense-trained model at inference, so the model never learned to use it — and most 'efficient' kernels were slower than FlashAttention in practice.",
  how: "Three branches per query — compressed coarse blocks, finely selected blocks, and a local sliding window — combined by a learned gate, with kernels written to match GPU memory access from the start. Trained end to end.",
  buys: "Matches or beats full attention on general, long-context and reasoning benchmarks while giving real measured speedups at 64k in forward, backward AND decode — not just decode.",
  costs: "Serious kernel engineering; the design is tuned to specific hardware; three branches is more machinery than a single attention op.",
  pick: "When you are pretraining a long-context model yourself and can afford the kernel work.",
  note: "Distinct from DeepSeek's later DSA — the two are frequently conflated."
},
{
  id: "dsa", name: "DeepSeek Sparse Attention (DSA)", short: "Retrofit sparsity via a tiny indexer",
  date: "2025-09-29", dateNote: "Model release, not a paper first: DeepSeek-V3.2-Exp released 29 Sep 2025 (vLLM blog, same day). Full paper arXiv 2512.02556, Dec 2025",
  paper: "DeepSeek-V3.2-Exp / DeepSeek-V3.2",
  authors: "DeepSeek-AI", url: "https://arxiv.org/abs/2512.02556",
  tags: ["sparse", "memory"],
  bill: "NSA requires pretraining with sparsity. What if you already have a strong dense model and want the same efficiency without starting over?",
  how: "A 'lightning indexer' — a very small, few-head, FP8 scoring module — ranks which tokens each query should read; fine-grained top-k selection then does the expensive attention over just those. Added to V3.1-Terminus by continued training, warming up the indexer first with the main model frozen.",
  buys: "O(Lk) instead of O(L²) with a near-free selector, roughly 50% cheaper long-context inference, retrofitted onto an existing model rather than pretrained from scratch.",
  costs: "Selection is approximate — a needed token can be missed; adds a second scoring pathway to serve and debug; benefits concentrate in long contexts.",
  pick: "When you have a strong dense checkpoint and long-context serving cost is the problem.",
  note: "This is the 'compressed + sparse, with a small low-rank indexer' design, and it is distinct from NSA above — different paper, different year, routinely conflated."
},
{
  id: "drope", name: "DroPE", short: "Recalibrate rotations before annealing",
  date: "2026-06-01", dateNote: "LightningLM V4 / 'Reversible Foundations' (School of AI), arXiv 2606.07404. exact algorithm not publicly specified",
  paper: "Reversible Foundations: Training a 120B Sparse MoE through State-Preserving Scaling",
  authors: "The School of AI (LightningLM V4)", url: "https://arxiv.org/abs/2606.07404",
  tags: ["position", "extension"],
  bill: "RoPE is computable at 256k but a model trained at 8k never learned those rotation patterns. YaRN-style repairs happen after training; V4 wanted the fix inside the run.",
  how: "Positional recalibration applied during training, before the annealing phase, so the learning-rate schedule still has room to adapt to the new rotation regime. V4 trained at 8k and reported 256k — a 32× extension.",
  buys: "Extension earned during training rather than patched at inference, with the cooldown available to absorb the shift.",
  costs: "Least publicly documented mechanism here: the exact algorithm and which rotary dimensions it touches are not specified, so it cannot be independently reproduced or compared against YaRN on equal terms.",
  pick: "Only if you control pretraining and can schedule the recalibration before the anneal.",
  note: "Evidence boundary: I am reporting what the record supports, not a mechanism I can verify."
}
];

/* Eras: the mind-changes the timeline exposes. */
const ERAS = [
  { from: "2014-01-01", to: "2018-12-31", name: "Make it work",
    text: "Attention is invented, then made parallel. Position is bolted on as an afterthought — first a stored table, then a function, then a distance. Nobody is optimising cost yet; they are establishing that this thing models language." },
  { from: "2019-01-01", to: "2020-12-31", name: "The first cost panic",
    text: "T² becomes the enemy. A wave of approximations — sparse patterns, hashing, windows, linear kernels — all attacking compute. In the middle of it, one paper (MQA) attacks the KV cache instead and is almost entirely ignored." },
  { from: "2021-01-01", to: "2022-12-31", name: "Position matures, and exactness strikes back",
    text: "RoPE and ALiBi settle how position should work. Then FlashAttention shows the bottleneck was memory traffic, not FLOPs — exact attention gets 2–4× faster, and most of the approximation wave quietly loses its justification." },
  { from: "2023-01-01", to: "2023-12-31", name: "Everyone wants their memory back — and their context longer",
    text: "Serving cost is now the binding constraint, so MQA's 2019 idea returns as GQA. Simultaneously a scramble to stretch context on models already trained: PI, NTK-aware, YaRN — repairs applied after the fact. StreamingLLM explains a bug instead of trading a cost." },
  { from: "2024-01-01", to: "2026-12-31", name: "Compress, and re-try the old ideas natively",
    text: "MLA compresses the cache instead of discarding heads. Recurrence returns with a working write rule (DeltaNet, Gated DeltaNet). Sparsity returns too — but now trained end-to-end and hardware-aligned (NSA), or retrofitted with a tiny indexer (DSA). The field is re-running 2020's ideas with 2020's lesson learned." }
];
